//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lavorazioni_S
    {
        public string Commessa { get; set; }
        public short Fase { get; set; }
        public string Reparto { get; set; }
        public string Macchina { get; set; }
        public string DescLavorazione { get; set; }
        public string CodiceLavorazione { get; set; }
        public Nullable<decimal> StdOraStandard { get; set; }
        public Nullable<decimal> StdOraStorico { get; set; }
        public string StdMacchina { get; set; }
        public Nullable<int> Quantità { get; set; }
        public Nullable<byte> Moltiplicatore { get; set; }
        public Nullable<byte> Organico { get; set; }
        public Nullable<byte> TaglioPezzi { get; set; }
        public Nullable<decimal> CostoSegnatura { get; set; }
        public Nullable<decimal> CostoCopia { get; set; }
        public Nullable<decimal> Totale { get; set; }
        public Nullable<decimal> CostoAvv { get; set; }
        public Nullable<decimal> TotaleCosti { get; set; }
        public Nullable<System.DateTime> DataOraInizio { get; set; }
        public Nullable<System.DateTime> DataOraFine { get; set; }
        public Nullable<byte> MinutiAvv { get; set; }
        public string OreLavoro { get; set; }
        public Nullable<long> Colore { get; set; }
        public string Spedita { get; set; }
        public Nullable<int> VMacchina { get; set; }
    }
}
