//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iSysPrintEntities : DbContext
    {
        public iSysPrintEntities()
            : base("name=iSysPrintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lavorazioni_S> Lavorazioni_S { get; set; }
        public virtual DbSet<NiceLabel_S> NiceLabel_S1 { get; set; }
        public virtual DbSet<Prev_S> Prev_S { get; set; }
        public virtual DbSet<PRODUZIONE_S> PRODUZIONE_S { get; set; }
        public virtual DbSet<Stampanti_NiceLabel_S> Stampanti_NiceLabel_S { get; set; }
        public virtual DbSet<V_Presenti_S> V_Presenti_S { get; set; }
    }
}
