//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiceLabel_S
    {
        public int ID { get; set; }
        public string Macchina { get; set; }
        public string Commessa { get; set; }
        public string Titolo { get; set; }
        public int Lavorazione { get; set; }
        public string DescLavorazione { get; set; }
        public string Segnatura { get; set; }
        public Nullable<int> QuantitaFatta { get; set; }
        public Nullable<int> QuantitaSuBancale { get; set; }
        public System.DateTimeOffset Data { get; set; }
        public Nullable<int> Bancale { get; set; }
        public string Presenti { get; set; }
        public string Stato { get; set; }
        public string Edizione { get; set; }
        public string IPPistola { get; set; }
        public string sscc_code { get; set; }
    }
}
