//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prev_S
    {
        public int IdPrev { get; set; }
        public byte Versione { get; set; }
        public byte IdUtente { get; set; }
        public string CodCli { get; set; }
        public string Editore { get; set; }
        public string Ordine { get; set; }
        public string Titolo { get; set; }
        public string Stato { get; set; }
        public string DataOraIns { get; set; }
        public Nullable<System.DateTime> DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public Nullable<System.DateTime> DataConferma { get; set; }
        public Nullable<int> Prodotto { get; set; }
        public Nullable<byte> Campione { get; set; }
        public string Modificato { get; set; }
        public string RifPrev { get; set; }
        public string Note { get; set; }
        public int id { get; set; }
        public Nullable<int> id_commessa { get; set; }
    }
}
