//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUZIONE_S
    {
        public string Macchina { get; set; }
        public string Commessa { get; set; }
        public Nullable<short> Lavorazione { get; set; }
        public Nullable<short> IndiceLav { get; set; }
        public string CodLav { get; set; }
        public Nullable<short> StdOra { get; set; }
        public Nullable<System.DateTime> DataOraInizio { get; set; }
        public Nullable<System.DateTime> DataOraFine { get; set; }
        public Nullable<byte> Edizione { get; set; }
        public Nullable<byte> Segnatura { get; set; }
        public Nullable<int> QuantitàFatta { get; set; }
        public string Stato { get; set; }
    }
}
