//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stampanti_NiceLabel_S
    {
        public short ID { get; set; }
        public string Ip_Pda { get; set; }
        public string Ip_Stampante { get; set; }
    }
}
