//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintLabel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Presenti_S
    {
        public string macchina { get; set; }
        public string presenti { get; set; }
    }
}
